name: github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: yarn install
        working-directory: ./
        run: yarn

      - name: build
        working-directory: ./
        run: yarn build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: app-demo.aya-eiya.work
          enable_jekyll: false
